In [1]:
import pandas as pd
from pathlib import Path

In [2]:
dfw = pd.read_csv("weather1.0.csv")
dfw

,city_address,day_precip,day_precipcover,day_snow,day_windspeed,day_winddir,day_uvindex,day_sunrise,day_sunset,hour_temp,...,datetime,Clear,Ice,Snow,Overcast,Rain,Fog,Partially cloudy,Freezing Drizzle/Freezing Rain,anomaly
0,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.4,...,2022-02-24 00:00:00,0,0,0,1,0,0,0,0,False
1,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.4,...,2022-02-24 01:00:00,0,0,0,0,0,0,1,0,False
2,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.9,...,2022-02-24 02:00:00,0,0,0,1,0,0,0,0,False
3,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.3,...,2022-02-24 03:00:00,0,0,0,1,0,0,0,0,False
4,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,1.9,...,2022-02-24 04:00:00,0,0,0,1,0,0,0,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608230,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.3,...,2025-03-01 19:00:00,0,0,0,1,0,0,0,0,False
608231,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.8,...,2025-03-01 20:00:00,0,0,0,1,0,0,0,0,False
608232,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.0,...,2025-03-01 21:00:00,0,0,0,1,0,0,0,0,False
608233,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.7,...,2025-03-01 22:00:00,0,0,0,1,0,0,0,0,False
608234,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-2.1,...,2025-03-01 23:00:00,0,0,0,1,0,0,0,0,False

In [3]:
dfa = pd.read_csv('alarms-240222-010325.csv', delimiter = ";")
dfa

,id,region_id,region_city,all_region,start,end
0,52432,12,Львівська обл.,1,2022-02-24 07:43:17,2022-02-24 09:52:28
1,53292,23,Чернігівська обл.,1,2022-02-24 14:00:43,2022-02-24 17:11:43
2,52080,3,Вінницька обл.,1,2022-02-24 15:40:42,2022-02-24 16:10:42
3,52857,19,Харківська обл.,1,2022-02-24 20:11:47,2022-02-24 20:59:47
4,52700,18,Тернопільська обл.,1,2022-02-25 01:59:36,2022-02-25 09:00:19
...,...,...,...,...,...,...
55783,158642,14,Одеська обл.,1,2025-03-01 21:49:30,2025-03-01 23:24:45
55784,158635,9,Київська обл.,1,2025-03-01 22:20:51,2025-03-02 01:38:57
55785,158636,9,Київ,0,2025-03-01 22:52:10,2025-03-02 00:55:18
55786,158617,3,Вінницька обл.,1,2025-03-01 23:26:07,2025-03-02 02:44:07
55787,158629,6,Житомирська обл.,1,2025-03-01 23:26:07,2025-03-02 02:43:26

In [4]:
dfa.columns

Index(['id', 'region_id', 'region_city', 'all_region', 'start', 'end'], dtype='object')

In [5]:
dfw.columns

Index(['city_address', 'day_precip', 'day_precipcover', 'day_snow',
       'day_windspeed', 'day_winddir', 'day_uvindex', 'day_sunrise',
       'day_sunset', 'hour_temp', 'hour_humidity', 'hour_precip',
       'hour_precipprob', 'hour_snow', 'hour_windspeed', 'hour_winddir',
       'hour_pressure', 'hour_visibility', 'hour_cloudcover', 'hour_uvindex',
       'datetime', 'Clear', 'Ice', 'Snow', 'Overcast', 'Rain', 'Fog',
       'Partially cloudy', 'Freezing Drizzle/Freezing Rain', 'anomaly'],
      dtype='object')

In [6]:
!pip install tqdm

Requirement already satisfied: tqdm in c:\users\roman\miniconda3\envs\work\lib\site-packages (4.67.1)
Requirement already satisfied: colorama in c:\users\roman\miniconda3\envs\work\lib\site-packages (from tqdm) (0.4.6)

In [7]:
import pandas as pd

# Ensure datetime columns are in datetime format
dfa['start'] = pd.to_datetime(dfa['start'])
dfa['end'] = pd.to_datetime(dfa['end'])
dfw['datetime'] = pd.to_datetime(dfw['datetime'])

# Mapping dictionary
ukr_to_eng_oblasts = {
    'Львівська обл.': 'Lviv',
    'Чернігівська обл.': 'Chernihiv',
    'Вінницька обл.': 'Vinnytsia',
    'Харківська обл.': 'Kharkiv',
    'Тернопільська обл.': 'Ternopil',
    'Одеська обл.': 'Odesa',
    'Дніпропетровська обл.': 'Dnipro',
    'Запорізька обл.': 'Zaporozhye',
    'Полтавська обл.': 'Poltava',
    'Сумська обл.': 'Sumy',
    'Житомирська обл.': 'Zhytomyr',
    'Київська обл.': 'Kyiv',
    'Черкаська обл.': 'Cherkasy',
    'Кіровоградська обл.': 'Kropyvnytskyi',
    'Миколаївська обл.': 'Mykolaiv',
    'Хмельницька обл.': 'Khmelnytskyi',
    'Рівненська обл.': 'Rivne',
    'Івано-Франківська обл.': 'Ivano-Frankivsk',
    'Закарпатська обл.': 'Uzhgorod',
    'Луганська обл.': 'Luhansk',
    'Донецька обл.': 'Donetsk',
    'АР Крим': 'Simferopol',
    'Севастополь': 'Simferopol', 
    'Київ': 'Kyiv'
}

# Translate region_city to match city_address
dfa['region_city_eng'] = dfa['region_city'].map(ukr_to_eng_oblasts)

# Initialize 'alarms' column
dfw['alarms'] = 0

# Function to count overlapping alerts
def count_alarms(row):
    city = row['city_address']
    t_start = row['datetime']
    t_end = t_start + pd.Timedelta(hours=1)
    
    mask = (
        (dfa['region_city_eng'] == city) &
        (dfa['start'] <= t_end) &
        (dfa['end'] >= t_start)
    )
    return mask.sum()

# Optional: show progress bar
from tqdm import tqdm
tqdm.pandas()

# Apply function
dfw['alarms'] = dfw.progress_apply(count_alarms, axis=1)

100%|█████████████████████████████████████████████████████████████████████████| 608235/608235 [24:46<00:00, 409.12it/s]

In [9]:
dfw

,city_address,day_precip,day_precipcover,day_snow,day_windspeed,day_winddir,day_uvindex,day_sunrise,day_sunset,hour_temp,...,Clear,Ice,Snow,Overcast,Rain,Fog,Partially cloudy,Freezing Drizzle/Freezing Rain,anomaly,alarms
0,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.4,...,0,0,0,1,0,0,0,0,False,0
1,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.4,...,0,0,0,0,0,0,1,0,False,0
2,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.9,...,0,0,0,1,0,0,0,0,False,0
3,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.3,...,0,0,0,1,0,0,0,0,False,0
4,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,1.9,...,0,0,0,1,0,0,0,0,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608230,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.3,...,0,0,0,1,0,0,0,0,False,0
608231,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.8,...,0,0,0,1,0,0,0,0,False,1
608232,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.0,...,0,0,0,1,0,0,0,0,False,1
608233,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.7,...,0,0,0,1,0,0,0,0,False,1
608234,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-2.1,...,0,0,0,1,0,0,0,0,False,1

In [11]:
dfw.describe()

,day_precip,day_precipcover,day_snow,day_windspeed,day_winddir,day_uvindex,hour_temp,hour_humidity,hour_precip,hour_precipprob,...,datetime,Clear,Ice,Snow,Overcast,Rain,Fog,Partially cloudy,Freezing Drizzle/Freezing Rain,alarms
count,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,...,608235,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000,608235.000000
mean,2.095817,6.553236,0.121145,18.545865,191.153775,4.804640,10.719585,72.889725,0.087358,6.553224,...,2023-08-28 23:55:04.730573056,0.196802,0.000002,0.016964,0.404048,0.059679,0.000003,0.398369,0.000100,0.188133
min,0.000000,0.000000,0.000000,2.500000,0.000000,0.000000,-50.300000,8.460000,0.000000,0.000000,...,2022-02-24 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,14.000000,98.200000,2.000000,2.400000,59.300000,0.000000,0.000000,...,2022-11-26 12:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.100000,4.170000,0.000000,18.000000,195.600000,5.000000,10.200000,77.430000,0.000000,0.000000,...,2023-08-29 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.092000,8.330000,0.000000,22.000000,287.000000,7.000000,18.400000,89.050000,0.000000,0.000000,...,2024-05-30 12:00:00,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,306.000000,100.000000,16.100000,90.000000,360.000000,10.000000,60.400000,100.000000,300.000000,100.000000,...,2025-03-01 23:00:00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,5.000000
std,10.686203,12.103634,0.662885,6.887745,106.205077,2.653039,9.788004,19.456807,2.141677,24.746285,...,NaN,0.397582,0.001282,0.129136,0.490707,0.236892,0.001813,0.489563,0.010014,0.426658

In [12]:
dfw.columns

Index(['city_address', 'day_precip', 'day_precipcover', 'day_snow',
       'day_windspeed', 'day_winddir', 'day_uvindex', 'day_sunrise',
       'day_sunset', 'hour_temp', 'hour_humidity', 'hour_precip',
       'hour_precipprob', 'hour_snow', 'hour_windspeed', 'hour_winddir',
       'hour_pressure', 'hour_visibility', 'hour_cloudcover', 'hour_uvindex',
       'datetime', 'Clear', 'Ice', 'Snow', 'Overcast', 'Rain', 'Fog',
       'Partially cloudy', 'Freezing Drizzle/Freezing Rain', 'anomaly',
       'alarms'],
      dtype='object')

In [14]:
dfw.to_csv("df_alt1.csv", index=False)

In [2]:
current_dir = Path.cwd()

In [3]:
isw_data_path = current_dir.parent / 'isw_processing' / 'isw_data_without_num_with_stopword.csv'

In [4]:
df_isw = pd.read_csv(isw_data_path, delimiter=",")

In [17]:
import pandas as pd

df_isw['date'] = pd.to_datetime(df_isw[['Year', 'Month', 'Day']]).dt.date
dfw['date'] = pd.to_datetime(dfw['datetime']).dt.date

dfw = dfw.merge(df_isw[['date', 'text_vector']], on='date', how='left')

In [18]:
dfw

,city_address,day_precip,day_precipcover,day_snow,day_windspeed,day_winddir,day_uvindex,day_sunrise,day_sunset,hour_temp,...,Snow,Overcast,Rain,Fog,Partially cloudy,Freezing Drizzle/Freezing Rain,anomaly,alarms,date,text_vector
0,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.4,...,0,1,0,0,0,0,False,0,2022-02-24,NaN
1,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.4,...,0,0,0,0,1,0,False,0,2022-02-24,NaN
2,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.9,...,0,1,0,0,0,0,False,0,2022-02-24,NaN
3,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.3,...,0,1,0,0,0,0,False,0,2022-02-24,NaN
4,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,1.9,...,0,1,0,0,0,0,False,0,2022-02-24,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608230,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.3,...,0,1,0,0,0,0,False,0,2025-03-01,0.010219
608231,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.8,...,0,1,0,0,0,0,False,1,2025-03-01,0.010219
608232,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.0,...,0,1,0,0,0,0,False,1,2025-03-01,0.010219
608233,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.7,...,0,1,0,0,0,0,False,1,2025-03-01,0.010219
608234,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-2.1,...,0,1,0,0,0,0,False,1,2025-03-01,0.010219

In [19]:
dfw.isna().sum()

city_address                          0
day_precip                            0
day_precipcover                       0
day_snow                              0
day_windspeed                         0
day_winddir                           0
day_uvindex                           0
day_sunrise                           0
day_sunset                            0
hour_temp                             0
hour_humidity                         0
hour_precip                           0
hour_precipprob                       0
hour_snow                             0
hour_windspeed                        0
hour_winddir                          0
hour_pressure                         0
hour_visibility                       0
hour_cloudcover                       0
hour_uvindex                          0
datetime                              0
Clear                                 0
Ice                                   0
Snow                                  0
Overcast                              0
Rain                                  0
Fog                                   0
Partially cloudy                      0
Freezing Drizzle/Freezing Rain        0
anomaly                               0
alarms                                0
date                                  0
text_vector                       12696
dtype: int64

In [20]:
dfw.fillna(0)

,city_address,day_precip,day_precipcover,day_snow,day_windspeed,day_winddir,day_uvindex,day_sunrise,day_sunset,hour_temp,...,Snow,Overcast,Rain,Fog,Partially cloudy,Freezing Drizzle/Freezing Rain,anomaly,alarms,date,text_vector
0,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.4,...,0,1,0,0,0,0,False,0,2022-02-24,0.000000
1,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.4,...,0,0,0,0,1,0,False,0,2022-02-24,0.000000
2,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.9,...,0,1,0,0,0,0,False,0,2022-02-24,0.000000
3,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,2.3,...,0,1,0,0,0,0,False,0,2022-02-24,0.000000
4,Lutsk,0.118,4.17,0.1,15.5,252.7,1.0,07:13:36,17:51:06,1.9,...,0,1,0,0,0,0,False,0,2022-02-24,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608230,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.3,...,0,1,0,0,0,0,False,0,2025-03-01,0.010219
608231,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.8,...,0,1,0,0,0,0,False,1,2025-03-01,0.010219
608232,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.0,...,0,1,0,0,0,0,False,1,2025-03-01,0.010219
608233,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-1.7,...,0,1,0,0,0,0,False,1,2025-03-01,0.010219
608234,Poltava,0.000,0.00,0.0,12.2,164.8,4.0,06:24:29,17:24:37,-2.1,...,0,1,0,0,0,0,False,1,2025-03-01,0.010219

In [21]:
dfw.to_csv("df_alt2.csv", index=False)

In [5]:
telegram_data_path = current_dir.parent / 'telegram_processing' / 'average_telegram_vectors.csv'

In [6]:
df_tg = pd.read_csv(telegram_data_path)

In [ ]:
df = pd.concat([dfw, df_tg], axis=1, join='outer')

col_indexes = [i for i, col in enumerate(df.columns) if col == 'datetime']
col_data = df.iloc[:, col_indexes[-1]]

df = df.drop(columns='datetime')

df.insert(20, 'datetime', col_data)

In [ ]:
df.to_csv('df_alt3.csv', index=False)